language: node_js
node_js:
    - "0.10"
addons:
    code_climate:
        repo_token: 8f7a4b9ea20b756fb04f330d417f71d89d8946d3b3ec5a8b0dcda40e894153e8
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
